### PR TITLE
Implemented the front-end

### LINKED ISSUE #19: Improve the frontend of this app
Create a beautiful frontend for this app using any framework. Preferably bootstrap.

### PR DESCRIPTION
**Pull request by sudiptog81**
Closes #19.

PR Deployment live on  https://obscure-meadow-89402.herokuapp.com/

image

_This PR was made as part of Hacktoberfest 2020. Add `hacktoberfest-accepted` label if approved._

### CODE REVIEW

**Comment by shoumikdey** [comment]
Hi!, Thanks for the PR. Can you add a feature: Whenever I upload a new image after a prediction, the text after 'prediction:' gets removed until the next prediction arrives.

**Comment by sudiptog81** [comment]
Sure, taking care of this in the next commit.

**Comment by sudiptog81** [comment]
demoBruteForce

**Comment by shoumikdey** [comment]
Nice work!

**Comment by shoumikdey** [comment]
@sudiptog81 Can you disable click on the button when the status goes to 'working'? Please send the new changes on a fresh PR.

**Comment by sudiptog81** [comment]
Addressed in #28.

**Pull request merged**
