### PR TITLE
linkedlist 

### PR DESCRIPTION
**Pull request by ayushil**
this is the best method for creating pull request

### CODE REVIEW

**Comment by shoumikdey** [comment]
@ayushil !Merged

**Comment by malakar-soham** [comment]
@ayushil , could you please explain the PR?

**Comment by DanBrown47** [comment]
@ayushil Should be reported as spam and invalid! This is so annoying stop spamming

**Comment by ayushil** [comment]
> @ayushil Should be reported as spam and invalid! This is so annoying stop spamming

can you explain me why are you considering this as spam ??

**Comment by shoumikdey** [comment]
> > @ayushil Should be reported as spam and invalid! This is so annoying stop spamming
> 
> can you explain me why are you considering this as spam ??

Why don't you explain why we shouldn't mark this as a spam?

**Comment by DanBrown47** [comment]
@ayushil This project is based on python and your commit is a basic Linked list written in C++, and you are asking me to explain why this is a spam, Please read the guidlines of hactoberfest and you will understand.

**Pull request closed without merging**
